// Angular build information, automatically generated by `angular-build-info`
export const buildInfo = {
    hash: "b308f7f",
    user: "Juri Adams",
    message: ":)",
    version: "1.0.0",
    timestamp: "June 23, 2020 09:34:45"
};
